services:
  mongodb:
    image: mongo:latest
    container_name: buy01DB
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./Backend/user
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - discovery-service
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

  discovery-service:
    build: ./Backend/discovery
    container_name: discovery-service
    restart: unless-stopped
    ports:
      - "8761:8761"

  gateway:
    build: ./Backend/gateway
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service


volumes:
  mongo_data: