services:
  discovery:
    build:
      context: ./Backend/discovery
    image: discovery:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=Backend/discovery"
    expose:
      - "8761"
      - "9000"
    networks:
      - buy01-network

  gateway:
    build:
      context: ./Backend/gateway
    image: gateway:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=Backend/gateway"
    ports:
      - "8443:8443"
    expose:
      - "9000"
    depends_on:
      discovery:
        condition: service_started
    env_file:
      - .env
    environment:
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN:-http://localhost:4200}
    networks:
      - buy01-network

  user:
    build:
      context: ./Backend/user
    image: user:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=Backend/user"
    expose:
      - "8081"
      - "9000"
    depends_on:
      users-mongodb:
        condition: service_healthy
      discovery:
        condition: service_started
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SPRING_MONGODB_URI: ${USER_DB_URI}
    networks:
      - buy01-network

  media:
    build:
      context: ./Backend/media
    image: media:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=Backend/media"
    expose:
      - "8082"
      - "9000"
    depends_on:
      media-mongodb:
        condition: service_healthy
      discovery:
        condition: service_started
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      R2_BUCKET: ${R2_BUCKET}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_PUBLIC_URL: ${R2_PUBLIC_URL}
      SPRING_MONGODB_URI: ${MEDIA_DB_URI}
    networks:
      - buy01-network

  product:
    build:
      context: ./Backend/product
    image: product:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=Backend/product"
    expose:
      - "8083"
      - "9000"
    depends_on:
      products-mongodb:
        condition: service_healthy
      discovery:
        condition: service_started
      kafka:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_MONGODB_URI: ${PRODUCT_DB_URI}
    networks:
      - buy01-network

  marketplace-ui:
    build:
      context: ./marketplace-ui
    image: marketplace-ui:${IMAGE_TAG:-latest}
    restart: unless-stopped
    labels:
      - "ci.path=marketplace-ui"
    ports:
      - "4200:80"
    depends_on:
      gateway:
        condition: service_started
    networks:
      - buy01-network
