spring.application.name=gateway
server.port=8443
management.server.port=9000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:buy01pass}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=gateway

cors.allowed-origin=${CORS_ALLOWED_ORIGIN:https://localhost:4200}

spring.cloud.gateway.server.webflux.routes[0].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service-users
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[2].id=media-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://media-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/media/**


spring.cloud.gateway.server.webflux.routes[3].id=product-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/product,/api/product/**



spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwtKey=${JWT_SECRET}
jwtExpiration=${JWT_EXPIRATION}
