sonar.projectKey=buy01-marketplace-ui
sonar.projectName=buy01 - marketplace-ui
sonar.sources=src
sonar.exclusions=**/*.spec.ts,node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/marketplace-ui/lcov.info
sonar.typescript.tsconfigPath=tsconfig.sonar.json