sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,src/environments/**,src/test-setup.ts
sonar.javascript.lcov.reportPaths=coverage/marketplace-ui/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.sonar.json
sonar.sourceEncoding=UTF-8
